language: objective-c

xcode_project: Learning.xcworkspace
xcode_scheme: LearningTests
osx_image: xcode8

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update --silent

script:
  - xcodebuild -list -workspace Learning.xcworkspace
  - xcodebuild clean test -workspace Learning.xcworkspace -scheme Learning
