language: objective-c

xcode_project: Learning.xcodeproj
xcode_scheme: Learning
osx_image: xcode8

before_install:
  - xcodebuild -list -project Learning.xcodeproj
  # - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  # - pod repo update --silent

script:
  - xcodebuild clean test -project Learning.xcodeproj -scheme Learning
