language: objective-c

xcode_project: Learning.xcworkspace
xcode_scheme: LearningTests
osx_image: xcode8

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update --quiet

script:
- set -o pipefail
# - xcodebuild -version
# - xcodebuild -showsdks
- xcodebuild clean build test -project Learning.xcworkspace -scheme LearningTests
